default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  host: localhost

development:
  <<: *default
  database: golf_development

test:
  <<: *default
  database: golf_test

production:
  <<: *default
  database: golf_production
  username: <%= ENV['GOLF_DATABASE_USERNAME'] %>
  password: <%= ENV['GOLF_DATABASE_PASSWORD'] %>

# production:
#  url: <%= ENV['DATABASE_URL'] %>
